language: r

# Be strict when checking our package
warnings_are_errors: true
bioc_required: true

# System dependencies for HTTP calling
apt_packages:
  - libcurl4-openssl-dev
  - libxml2-dev

r_binary_packages:
  - RUnit
  - Rcpp

# Install packages from github
r_github_packages:
  - zhengxwen/gdsfmt
  - zhengxwen/SNPRelate

